@baseUrl = http://localhost:3003/api/blogs
@blogId = 6430f2fcaf55e09903c36211
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjNmZmI3Y2ZlZTQ2NWM5ZWY4MDQyYjI1IiwiaWF0IjoxNjgwOTI5NDc1LCJleHAiOjE2ODA5MzMwNzV9.yZ-vHDMFtnmYUdutOm2vKdgdTAd_JkxJqfJ__mYjcLk
DELETE {{baseUrl}}/{{blogId}}
Authorization: Bearer {{token}}
